POST http://localhost:3001/api/blog/ HTTP/1.1
content-type: application/json
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjU2Zjk1Yzg2OTAxYWFiNzYzMjdiYiIsImlhdCI6MTYzNDA1Mjk5NywiZXhwIjoxNjM0MDUzMDAwfQ.1XyVtIeMm9DhQFzxAT4G_y8NxtYAYd8cdXvivkqHiMQ

{
  "title": "Which jobs help people the most?",
  "author": "Benjamin Todd",
  "url": "https://80000hours.org/career-guide/high-impact-jobs/#approach-1-earning-to-give",
  "likes": 100,
  "userId": "617826538ea1abb01e3dab6e"
}

###
POST http://localhost:3001/api/blog/617dcfc1befb128d9ed07701/comment HTTP/1.1
content-type: application/json

{
  "content": "haven't read this yet"
}

###
POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json

# {
#   "username": "camariana",
#   "password": "secrete",
#   "name": "A Camariana"
# }

{
  "username": "mluukkai",
  "password": "salainen",
  "name": "Matti Luukkainen"
}


###
POST http://localhost:3001/login HTTP/1.1
content-type: application/json

{
  "username": "camariana",
  "password": "secrete"
}