GET http://localhost:3001/user/ HTTP/1.1
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjU2Zjk1Yzg2OTAxYWFiNzYzMjdiYiIsImlhdCI6MTYzNDAzNzg0NSwiZXhwIjoxNjM0MDM3ODQ4fQ.DV-e1RDjpq82gz7dN6D67ffeRCBF0k2oUVncC8Uno8w

###
GET http://localhost:3001/api/blog/ HTTP/1.1